#!/usr/bin/env bash
# wrappers/generate.sh -- emit build-time compiler wrappers that pin the ISA.
#
# WHY THIS EXISTS
#
# '-march' is last-wins on a gcc command line, and every mechanism we have for
# setting flags -- CFLAGS, CXXFLAGS, conda's activate.d, a configure argument --
# injects them FIRST.  So any build system that appends its own -march silently
# beats whatever baseline we asked for.  That is not hypothetical: Kokkos
# autodetects the host architecture and arrives with Trilinos, and PETSc's
# --download- TPLs each carry their own build system and their own opinions.
#
# The only place left to stand is between the build system and the compiler.
# A wrapper appends '-march=<baseline>' AFTER everything the caller passed, so
# it wins by the same rule that was defeating us.  Note what that means: this is
# a hard CAP, not a floor.  '-mavx2 -march=x86-64-v2' yields no AVX2, because
# '-march=' resets the entire feature set and ours is last.  That is the
# intended semantics -- we are declaring what the artifact may contain.
#
# Precedent: NCAR/ncarcompilers does the same thing for the same reason.  This
# is adapted rather than vendored; that implementation is bound to NCAR's module
# environment, and we need roughly a tenth of it.
#
# SCOPE: build-time only.  These wrappers live under $WORK, never inside $STACK,
# and are therefore not in the tarball.  A customer compiling against the shipped
# stack uses their own compiler, and nothing here follows the artifact out.
#
# WHAT IS AND IS NOT WRAPPED
#
# The underlying compilers are wrapped, including conda's triplet names.
# 'mpicc' and friends are deliberately NOT, because mpicc is a wrapper that
# invokes the triplet-named compiler -- which is already wrapped.  Wrapping both
# would inject twice.  (Harmless in effect, since the flag is idempotent, but it
# makes command lines unreadable and hides which layer is responsible.)
#
# 'cpp' is not wrapped either: the preprocessor emits no instructions, so there
# is nothing to constrain, and -march on a bare preprocessor run is noise.
set -euo pipefail

: "${STACK:?}" "${WORK:?}" "${ISA_BASELINE:?}"

OUT="${WORK}/wrappers"
BIN="${OUT}/bin"
ON_NATIVE="${WRAPPER_ON_NATIVE:-error}"     # error | warn

rm -rf "${OUT}"
mkdir -p "${BIN}"

#------------------------------------------------------------------------------
# The wrapper body, identical for every tool.  Written once here and appended to
# a per-tool header that supplies 'real', 'baseline' and 'on_native'.
body () {
cat <<'BODY'

# --- introspection passes through untouched -----------------------------------
#
# PETSc's configure interrogates the compiler and parses what comes back;
# libtool and cmake do the same.  Appending a flag to '--version' would at best
# be ignored and at worst change the output, so these are exec'd verbatim.
#
# Bare '-v' is the awkward one: alone it means "print version and search dirs",
# but combined with sources it means "be verbose while compiling".  Only the
# former is introspection, so it passes through only when it is the whole
# command line.
if [ "$#" -eq 1 ] && [ "$1" = "-v" ]; then exec "$real" "$@"; fi
for a in "$@"; do
  case "$a" in
    --version|-dumpversion|-dumpfullversion|-dumpmachine|-dumpspecs|-print-*|--help|--target-help|-V|-qversion)
      exec "$real" "$@" ;;
  esac
done

# --- host detection is a bug, not a preference --------------------------------
#
# '-march=native' would in fact be neutralised by the baseline we append after
# it, so this check is not needed for correctness.  It is here for visibility: a
# build system reaching for 'native' is doing host detection, and the -march it
# emitted is rarely the only place that shows up.  Silently correcting it would
# hide exactly the thing worth looking at.  WRAPPER_ON_NATIVE=warn downgrades it.
for a in "$@"; do
  case "$a" in
    -march=native|-mcpu=native)
      msg="$(basename "$0"): refusing '$a' -- this build detects the host CPU.
  The artifact must run on the declared baseline ($baseline), and host
  detection means there is probably more of it than this one flag.
  Find where it comes from; set WRAPPER_ON_NATIVE=warn to proceed anyway."
      if [ "$on_native" = warn ]; then
        echo "$msg" >&2
      else
        echo "$msg" >&2; exit 1
      fi ;;
  esac
done

# Last, so it wins.  Nothing is written to stdout: configure runs thousands of
# compile tests and parses their output, and a chatty wrapper breaks them in
# ways that surface much later as a nonsense configure result.
exec "$real" "$@" "$baseline"
BODY
}

emit () {
  local n="$1" real="$2"
  {
    echo '#!/usr/bin/env bash'
    echo '# GENERATED by wrappers/generate.sh -- do not edit.  Build-time only.'
    echo "real='${real}'"
    echo "baseline='-march=${ISA_BASELINE}'"
    echo '# Overridable at run time, so a build that trips it can be re-run without'
    echo '# regenerating the wrappers -- the point is to be seen, not immovable.'
    echo "on_native=\"\${WRAPPER_ON_NATIVE:-${ON_NATIVE}}\""
    body
  } > "${BIN}/${n}"
  chmod +x "${BIN}/${n}"
}

#------------------------------------------------------------------------------
# What conda actually installed.  It ships triplet-prefixed compilers --
# 'aarch64-conda-linux-gnu-gcc' and friends -- and, depending on the solve, may
# or may not add bare aliases.
names=()
for t in "${STACK}"/bin/*-gcc "${STACK}"/bin/*-g++ "${STACK}"/bin/*-cc \
         "${STACK}"/bin/*-c++ "${STACK}"/bin/*-gfortran \
         "${STACK}"/bin/cc "${STACK}"/bin/gcc "${STACK}"/bin/c++ \
         "${STACK}"/bin/g++ "${STACK}"/bin/gfortran; do
  [ -e "${t}" ] && names+=( "$(basename "${t}")" )
done
[ "${#names[@]}" -gt 0 ] || { echo "no compilers under ${STACK}/bin" >&2; exit 1; }

declare -A resolved=()
printf '  %-40s %s\n' 'wrapper' 'execs'
for n in $(printf '%s\n' "${names[@]}" | sort -u); do
  src="${STACK}/bin/${n}"
  [ -x "${src}" ] || continue

  # Resolve all the way to the real binary rather than to the next symlink.
  # Two reasons, and both have teeth:
  #
  #   1. Recursion.  Our wrapper dir sits AHEAD of $STACK/bin on PATH, so a
  #      wrapper that exec'd its own basename would call itself forever.
  #      Baking in the absolute resolved path removes the possibility rather
  #      than relying on PATH manipulation to avoid it.
  #   2. Double wrapping.  '$STACK/bin/cc' is a symlink to the triplet 'cc',
  #      which is a symlink to the triplet 'gcc'.  Resolving one level would
  #      make the cc wrapper exec the triplet cc -- which is also wrapped.
  real="$(readlink -f "${src}")"
  [ -x "${real}" ] || continue

  # gcc's driver decides C vs C++ linking from its own name, so the resolved
  # target must stay in the same language family as what we are wrapping.  If
  # conda ever rearranges the symlinks, fail loudly here rather than shipping a
  # 'c++' that quietly links without libstdc++.
  case "${n}" in
    *c++|*g++)         want=g++ ;;
    *gfortran)         want=gfortran ;;
    *)                 want=gcc ;;
  esac
  case "$(basename "${real}")" in
    *g++|*c++)  got=g++ ;;
    *gfortran)  got=gfortran ;;
    *)          got=gcc ;;
  esac
  [ "${want}" = "${got}" ] || {
    echo "refusing: ${n} resolves to $(basename "${real}") (${got}, expected ${want})" >&2
    exit 1
  }

  emit "${n}" "${real}"
  resolved["${got}"]="${real}"
  printf '  %-40s %s\n' "${n}" "${real#"${STACK}"/}"
done

#------------------------------------------------------------------------------
# Bare aliases, when conda did not provide them.
#
# conda ships ONLY triplet-named compilers, so a build system that falls back to
# plain 'cc' or 'gcc' -- and plenty do -- has nothing to land on inside the
# stack.  What it lands on instead is whatever the base image provides, and
# docker/bases.env makes that a knob.
#
# The current almalinux:9 builder has no cc, gcc, c++ or clang at all (checked),
# so there the fallback is a loud "command not found".  On an image that does
# ship a compiler the same fallback compiles against the HOST toolchain -- host
# libstdc++, host glibc headers, none of the baseline -- and links, and runs on
# the build machine.  Providing our own 'cc' first on PATH makes the outcome
# independent of which base image someone points this at.
for pair in "cc:gcc" "gcc:gcc" "c++:g++" "g++:g++" "gfortran:gfortran"; do
  alias_name="${pair%%:*}" family="${pair##*:}"
  [ -e "${BIN}/${alias_name}" ] && continue
  [ -n "${resolved[${family}]:-}" ] || continue
  emit "${alias_name}" "${resolved[${family}]}"
  printf '  %-40s %s  (alias)\n' "${alias_name}" "${resolved[${family}]#"${STACK}"/}"
done

wrapped="$(ls -1 "${BIN}" | wc -l)"

#------------------------------------------------------------------------------
# Binutils, under the names build systems actually look for.
#
# conda installs binutils only under triplet-prefixed names --
# x86_64-conda-linux-gnu-ar and friends -- and docker/Dockerfile.builder
# installs none at all, deliberately: binutils compiles and inspects, so the
# conda env owns it and the host does not.  The gap between those two facts is
# that anything asking for a bare 'ar' falls through to whatever the base image
# happens to carry, and that is a lottery.  Measured across the five supported
# bases: almalinux 8 and 9 ship ar, ranlib and objdump; ubuntu 22.04, ubuntu
# 24.04 and opensuse/leap:15 ship none of them.
#
# Three separate consumers were living on that accident, and each failed
# differently and unhelpfully the first time anyone built on a Debian host:
# PETSc's configure ("Could not find a suitable archiver"), TriBITS' Fortran
# mangling probe ("CMAKE_AR-NOTFOUND qc libVerifyFortran.a"), and the ISA
# selftest's control scan (which reported nothing above the baseline because it
# had no disassembler to look with -- the worst of the three, since that one
# reads as a pass).
#
# The tracked recipes now also name their tools explicitly, which is the right
# fix for code we own.  These links are for the code we do NOT own: a site/
# package that calls 'ar' or 'strip' the way essentially every autotools
# project does, and which has no reason to know any of the above.  The point of
# this directory has always been to make tool resolution independent of the
# base image; binutils belongs in it for exactly the reason the compilers do.
#
# ld and as are deliberately NOT here.  The compiler driver locates those
# through its own -B paths, and putting ours ahead of it on PATH would be
# changing how things link rather than making a missing tool findable.
# The triplet is resolved once and the target named exactly, rather than globbed
# for.  A glob is actively wrong here: conda ships BOTH <triplet>-nm and
# <triplet>-gcc-nm (likewise ar and ranlib), the second being GCC's LTO wrapper
# rather than the binutils tool.  'ls *-nm | head -1' picks gcc-nm, because 'g'
# sorts before 'n' -- while the same expression picks the right thing for 'ar',
# because 'a' sorts before 'g'.  Measured, after writing it the wrong way first:
# a build asking for 'nm' would have quietly got the LTO wrapper.
triplet=""
for c in "${STACK}"/bin/*-gcc; do
  [ -x "${c}" ] || continue
  triplet="$(basename "${c}")"; triplet="${triplet%-gcc}"; break
done

shimmed=0
if [ -n "${triplet}" ]; then
  for tool in ar ranlib nm strip objdump objcopy readelf addr2line size strings c++filt; do
    [ -e "${BIN}/${tool}" ] && continue
    real="${STACK}/bin/${triplet}-${tool}"
    [ -x "${real}" ] || continue
    ln -s "${real}" "${BIN}/${tool}"
    printf '  %-40s %s  (binutils)\n' "${tool}" "${real#"${STACK}"/}"
    shimmed=$((shimmed + 1))
  done
else
  echo "  WARNING: no <triplet>-gcc in ${STACK}/bin; binutils not exposed" >&2
fi

#------------------------------------------------------------------------------
# env.sh: belt as well as braces.
#
# PATH order is the primary mechanism and covers any build that invokes the
# compiler by name.  MPICH's wrappers are the case it might not cover: mpicc
# runs the compiler recorded when mpich was built, and whether that is a bare
# name (PATH applies) or an absolute path (PATH does not) is mpich's choice, not
# ours.  MPICH_CC and friends override it either way, so setting them closes the
# gap without needing to know which it was.  OMPI_* does the same for OpenMPI.
{
  echo "# GENERATED by wrappers/generate.sh -- sourced by lib/build_common.sh"
  for pair in "CC:cc" "CXX:c++" "FC:gfortran" "F77:gfortran"; do
    var="${pair%%:*}" tool="${pair##*:}"
    [ -x "${BIN}/${tool}" ] || continue
    echo "export MPICH_${var}='${BIN}/${tool}'"
    echo "export OMPI_${var}='${BIN}/${tool}'"
  done
} > "${OUT}/env.sh"

echo "  ${wrapped} wrapper(s) in ${BIN}, pinning ${ISA_BASELINE}"
echo "  ${shimmed} binutils tool(s) exposed under their bare names"
